Rh predict
aramis-lab/clinicadl pull request #304
Opened 2022-04-13 09:37 UTC by ravih18

In this PR I merged the `save-tensor` command line into `predict` and added the option `--save_tensor` and `--save-nifti`.

This simplify a little bit the command line by gathering all inference command. Moreover it allows to perform evaluation and reconstruction in the same command.

2022-07-12 12:52 UTC, mdiazmel requested changes
Seems ok. Need to update the documentation (update the _Save reconstruction outputs_ section before merging.

2022-07-12 12:52 UTC, mdiazmel commented on clinicadl/predict/predict.py
>      This function loads a MAPS and predicts the global metrics and individual values
Could you please update the docstring fot this function by adding the description of the two new arguments?

2022-07-18 16:20 UTC, mdiazmel commented
@ravih18, I will take the liberty of applying a cherry-pick of commit 753a99c in your PR, in order to allow running again the CI (after merging PR #322).

2022-07-21 10:09 UTC, camillebrianceau approved these changes

2022-07-27 09:41 UTC, mdiazmel approved these changes
LGTM!
Seems that there are still some conflicts to solve. I'll try to solve them.

2022-07-27 11:02 UTC, merged