Refactoring tsvtool
aramis-lab/clinicadl pull request #338
Opened 2022-08-04 14:00 UTC by camillebrianceau

**TSVTOOL REFACTORING**
 
#313  
- [x] Rename `tsvtool` --> `tsvtools`
- [x] Rename `extract` --> `prepare-data`
- [x] Rename `split`/ `kfold` --> ??

#310  Remove `restrict`command 

**GETLABELS**

#311  Change diagnosis into group and subgroup 

#258 For now, each `group` (CN --> MCI --> AD) has a `subgroup`( p, s, r, us, uk)  and this subgroup represents the evolution of the disease during time_horizon :
- p : progressive
- r: regressive 
- s: stable 
- us: unstable
- uk: unknown

#233 done

#312 Now there is only one tsv with group and subgroup and the group columns is what was called diagnosis in the old version of get labels. 

Now, instead of giving path to the missing_mods directory and merge.tsv file, we only give a BIDS_directory and the pipeline will perform `clinica iotools merge-tsv`and `clinica iotools check_missings_modalities` inside the `get labels` pipeline 

The command line for get labels is:
> `clinicadl tsvtools getlabels BIDS_directory/ get_labels_directory/ -d CN -d pMCI`

input : BIDS directory and GETLABELS directory 
output : (in getlabels directory)   getlabels.json + getlabels.tsv + merge.tsv + missing_mods_directory 

**SPLIT AND K-FOLD**

#314 almost done 

**CHANGES THAT NEED TO BE DISCUSSED** 

- `uk`  is unknown subgroup : if there are not enough sessions to assess the reliability of the label but no changes were spotted. I chose to put `uk` for each last session.
- I added a directory at the beginning of the `getlabels` function showing the progression of Alzheimer's disease : {CN:0, MCI:1, AD:2 }.
I added the option --stability_dict, no need to keep it, but if wanted, we can pass a list of diagnoses into the command line in order of the disease progression so we can work with other disesases. 
- if you add the option `--diagnosis` with a group, you will get all subjects for whom, for at least one session, the diagnostic is this group.
- if you add the option `--diagnosis` with a subgroup, you will get all subjects that have this subgroup

2022-08-04 14:00 UTC, pep8speaks commented
Hello @camillebrianceau! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:



* In the file [`clinicadl/tsvtools/getlabels/getlabels.py`](https://github.com/aramis-lab/clinicadl/blob/e8f725f4fda8ec9a111a09b50653836de854b961/clinicadl/tsvtools/getlabels/getlabels.py):

> [Line 274:13](https://github.com/aramis-lab/clinicadl/blob/e8f725f4fda8ec9a111a09b50653836de854b961/clinicadl/tsvtools/getlabels/getlabels.py#L274): [E266](https://duckduckgo.com/?q=pep8%20E266) too many leading '#' for block comment
> [Line 282:17](https://github.com/aramis-lab/clinicadl/blob/e8f725f4fda8ec9a111a09b50653836de854b961/clinicadl/tsvtools/getlabels/getlabels.py#L282): [E265](https://duckduckgo.com/?q=pep8%20E265) block comment should start with '# '
> [Line 296:17](https://github.com/aramis-lab/clinicadl/blob/e8f725f4fda8ec9a111a09b50653836de854b961/clinicadl/tsvtools/getlabels/getlabels.py#L296): [E265](https://duckduckgo.com/?q=pep8%20E265) block comment should start with '# '
> [Line 312:17](https://github.com/aramis-lab/clinicadl/blob/e8f725f4fda8ec9a111a09b50653836de854b961/clinicadl/tsvtools/getlabels/getlabels.py#L312): [E265](https://duckduckgo.com/?q=pep8%20E265) block comment should start with '# '

2022-08-31 08:58 UTC, ravih18 commented on clinicadl/tsvtools/get_metadata/get_metadata.py
> +def get_metadata():
This has to be done

2022-08-31 08:59 UTC, ravih18 commented on clinicadl/tsvtools/getlabels/getlabels_cli.py
> +    help="Time horizon to analyse stability of subjects.",
It would be great to specify in the description that this is the stability of the label in the case of a progressive disease

2022-08-31 09:50 UTC, ravih18 commented on clinicadl/tsvtools/getlabels/getlabels_cli.py
> +    "Will always keep the group, subgroup, age and sex needed for the split procedure.",
Maybe be more precise here, define that the group is the diagnosis in most case and the subgroup the progression in the case of progressive disease.

2022-08-31 09:50 UTC, ravih18 commented on clinicadl/tsvtools/getlabels/getlabels_cli.py
> +@click.option(
This can be moved in the `option.py` file as it might be useful for other CLI.

2022-08-31 09:57 UTC, ravih18 commented on clinicadl/tsvtools/kfold/kfold_cli.py
> +    FORMATTED_DATA_TSV is the path to the output of tsvtool getlabels command.
Path to the tsv or to the getlabel dir ?

2022-08-31 09:59 UTC, ravih18 commented on clinicadl/utils/cli_param/argument.py
>  dataset = click.argument("dataset", type=click.Choice(["AIBL", "OASIS"]))
Maybe this can be removed because it was only used in restrict.

2022-08-31 10:00 UTC, ravih18 commented on clinicadl/utils/cli_param/option.py
>      default=("AD", "CN"),
Default may be sAD and sCN.

2022-08-31 10:01 UTC, ravih18 commented on clinicadl/utils/cli_param/option.py
> +    type=click.Choice(
This will be improved

2022-08-31 10:03 UTC, ravih18 commented on clinicadl/tsvtools/split/split_cli.py
> +    FORMATTED_DATA_TSV is the path to the tsv file where the outputs of tsvtool getlabels command are stored.
Same is it the tsv file or getlables directory ?

2022-08-31 13:33 UTC, ravih18 commented on clinicadl/tsvtools/prepare_experiment/prepare_experiment_cli.py
> +    default="split",
I think default should be kfold here.

2022-08-31 13:34 UTC, ravih18 commented on clinicadl/tsvtools/prepare_experiment/prepare_experiment_cli.py
> +    type=click.Choice(["split", "kfold"]),
Choices name should be coherent with help string.

2022-08-31 15:59 UTC, ravih18 commented on clinicadl/tsvtools/getlabels/getlabels.py
> +from cmath import nan
Idk if this is used

2022-08-31 15:59 UTC, ravih18 commented on clinicadl/tsvtools/getlabels/getlabels.py
> +from requests import get
same

2022-08-31 16:04 UTC, ravih18 commented on clinicadl/tsvtools/getlabels/getlabels.py
> +        stability_dict: List of all the diagnoses that can be encountered in order of the disease progression.
We need to find a solution to improve this.

2022-08-31 16:12 UTC, ravih18 commented on clinicadl/tsvtools/split/split.py
> +from math import nan
same

2022-08-31 16:14 UTC, ravih18 commented on docs/TSVTools.md
> +    ├── getlabels.json
maybe the file and folder can be directly named labels instead of getlabels ?

2022-08-31 16:18 UTC, ravih18 reviewed
I made a first review of this PR.

It looks good, but I think it would be great to have an example with the different cases and see how it works (already on adni maybe ?). This example could then be used for a future test set ?

There are still some variable that could be renamed from `xxx_path` to `xxx_directory/dir/file extension`. I saw that there is already an effort that was made but some old variable are still miss named.

2022-09-08 16:13 UTC, ravih18 reviewed
There is an empty file nae `blabla.tsv`.

It looks like the reference getlabels.tsv and getlabels2.tsv are missing the subgroup column.

2022-10-04 16:22 UTC, mdiazmel requested changes
Hi @camillebrianceau ,

Thanks for this **huge** PR. Requested changes concerns mainly the docstrings and some texts. Also try to add typing hints to the new functions that you create. 

About the files in the folder `tests/data/tsvtool/`, these files will be in the new data ci package? If yes, I suppose that they can be removed from this repository.

2022-10-04 16:22 UTC, mdiazmel commented on clinicadl/tsvtools/analysis/analysis_cli.py
> +    FORMATTED_DATA_TSV is the outputs of `clinicadl tsvtool getlabels`.
```suggestion
    FORMATTED_DATA_TSV is the output of `clinicadl tsvtool getlabels`.
```

2022-10-04 16:22 UTC, mdiazmel commented on clinicadl/tsvtools/analysis/analysis_cli.py
> +    demographics_analysis(merged_tsv, formatted_data_tsv, results_tsv, diagnoses)
Add docstring

2022-10-04 16:22 UTC, mdiazmel commented on clinicadl/tsvtools/get_metadata/get_metadata.py
> +def get_metadata(formatted_data_tsv, output_tsv, variables_of_interest=None):
Could you add typing to new functions in order to profit from type hints in the future? Also add docstrings, please.

2022-10-04 16:22 UTC, mdiazmel commented on clinicadl/tsvtools/getlabels/getlabels.py
> +    A method to get the subgroup for each sessions depending on their stability on the time horizon
Could you please switch this docstring to the numpy style?

2022-10-04 16:22 UTC, mdiazmel commented on clinicadl/tsvtools/getlabels/getlabels.py
> +    Removes sessions for which the diagnosis is not in the list provided (avoid to keep rMCI and pMCI in sMCI lists).
Switch to numpy style.

2022-10-04 16:22 UTC, mdiazmel commented on clinicadl/tsvtools/getlabels/getlabels.py
> +    Writes one TSV file based on merged_tsv and missing_mods.
Same than before, switch to numpy style

2022-10-04 16:22 UTC, mdiazmel commented on clinicadl/tsvtools/getlabels/getlabels.py
> +        f"output of clinica iotools check-missing-modalities : {missing_mods_directory}"
```suggestion
        f"output of clinica iotools check-missing-modalities: {missing_mods_directory}"
```

2022-10-04 16:22 UTC, mdiazmel commented on clinicadl/tsvtools/getlabels/getlabels.py
> +    logger.info(f"output of clinica iotools merge-tsv : {merge_tsv_path}")
```suggestion
    logger.info(f"output of clinica iotools merge-tsv: {merge_tsv_path}")
```

2022-10-04 16:22 UTC, mdiazmel commented on clinicadl/tsvtools/getlabels/getlabels_cli.py
> +    """Get labels in one tsv files.
```suggestion
    """Get labels in one tsv file.
```

2022-10-04 16:22 UTC, mdiazmel commented on clinicadl/tsvtools/getlabels/getlabels_cli.py
> +    This command will perform two others command inside :
```suggestion
    This command executes the two following commands :
```

2022-10-04 16:22 UTC, mdiazmel commented on clinicadl/tsvtools/kfold/kfold.py
> +    The output (the tsv file) will have two new columns :
Reformat docstring to numpy style.

2022-10-04 16:22 UTC, mdiazmel commented on clinicadl/tsvtools/kfold/kfold_cli.py
> +    FORMATTED_DATA_TSV is the path to the output of tsvtool getlabels command.
Same concern, is `FORMATTED_DATA_TSV` a folder or a tsv file?

2022-10-04 16:22 UTC, mdiazmel commented on clinicadl/tsvtools/split/split.py
> +def df_to_tsv(name: str, results_path: str, df, baseline: bool = False):
Add small docstring.

2022-10-04 16:22 UTC, mdiazmel commented on tests/test_tsvtool.py
> +data_ci_directory = "/network/lustre/iss02/aramis/projects/clinicadl/DATA_CI"
I suppose that this path will be remove in the PR #350  ... isn't?

2022-10-05 14:32 UTC, camillebrianceau commented
I think that this PR is ready to merge.
Some tests don't pass because the data needed are on dvc but we can test the tsvtools locally.

At the end, what is new ?

### TSVTOOL REFACTORING

https://github.com/aramis-lab/clinicadl/issues/313

- Rename tsvtool --> tsvtools
- Rename extract --> prepare-data
- Didn't rename split/ kfold  

[#310](https://github.com/aramis-lab/clinicadl/issues/310 )Remove restrict command

### GETLABELS

[#311](https://github.com/aramis-lab/clinicadl/issues/311) Change diagnosis into group and subgroup
--> Finally we don't have group and subgroup, we keep the diagnosis column but without the labels pMCI and sMCI but we added a new command `get-progression` to get the subgroup (see the first comment of this PR) in a column name progression.

https://github.com/aramis-lab/clinicadl/issues/312 Now there is only one tsv. 

Now, instead of giving path to the missing_mods directory and merge.tsv file, we only give a BIDS_directory and the pipeline will perform clinica iotools merge-tsvand clinica iotools check_missings_modalities inside the get labels pipeline

The command line for get labels is:
```
clinicadl tsvtools get-labels BIDS_directory/  -d CN -d pMCI
```

input : BIDS directory
output : (in getlabels directory) labels.json + labels.tsv + merge.tsv + missing_mods_directory

### SPLIT AND K-FOLD

[314](https://github.com/aramis-lab/clinicadl/issues/314) done

CHANGES THAT NEED TO BE DISCUSSED

- [ ] uk is unknown subgroup : if there are not enough sessions to assess the reliability of the label but no changes were spotted. I chose to put uk for each last session. 

- [ ] I added a directory at the beginning of the getlabels function showing the progression of Alzheimer's disease : {CN:0, MCI:1, AD:2 }.

- [ ] I added the option --stability_dict, no need to keep it, but if wanted, we can pass a list of diagnoses into the command line in order of the disease progression so we can work with other disesases.

- [ ] if you add the option --diagnosis with a group, you will get all subjects for whom, for at least one session, the diagnostic is this group.

- [ ] if you add the option --diagnosis with a subgroup, you will get all subjects that have this subgroup


I know that I still need to write the docs.

2022-10-05 16:00 UTC, mdiazmel requested changes
Just a couple of changes before merging!

2022-10-05 16:00 UTC, mdiazmel commented on clinicadl/tsvtools/get_metadata/get_metadata.py
> +    metadata_df: DataFrame, output_df: DataFrame, variables_of_interest=None
```suggestion
    metadata_df: pd.DataFrame, output_df: pd.DataFrame, variables_of_interest=None
```

2022-10-05 16:00 UTC, mdiazmel commented on clinicadl/tsvtools/get_metadata/get_metadata.py
> +) -> DataFrame:
```suggestion
) -> pd.DataFrame:
```

2022-10-05 16:00 UTC, mdiazmel commented on clinicadl/tsvtools/get_metadata/get_metadata.py
> +        result_df.to_csv(output_tsv, sep="\t")
`output_tsv` is not defined in current context.

2022-10-05 16:00 UTC, mdiazmel commented on clinicadl/tsvtools/get_metadata/get_metadata_cli.py
> +    results_directory = Path(data_tsv).parents[0]
Need to add `from pathlib import Path` at the header, no?

2022-10-05 16:00 UTC, mdiazmel commented on clinicadl/tsvtools/get_progression/get_progression.py
> +        data_directory = Path(output_tsv).parents[0]
Need to import Path from pathlib

2022-10-05 16:00 UTC, mdiazmel commented on clinicadl/tsvtools/get_progression/get_progression.py
> +        data_tsv = results_directory / "labels.tsv"
`data_tsv` is redefined here, but it's a parameter of the function.

2022-10-05 16:00 UTC, mdiazmel commented on clinicadl/tsvtools/get_progression/get_progression_cli.py
> +    DATA_TSV is the path to the tsv file with colmuns including ["participants_id", "session_id"]
```suggestion
    DATA_TSV is the path to the tsv file with columns including ["participants_id", "session_id"]
```

2022-10-05 16:00 UTC, mdiazmel commented on clinicadl/tsvtools/get_progression/get_progression_cli.py
> +    TIME_HORIZON is the time in months choosen to analyse the stability of the label (default is 36)
```suggestion
    TIME_HORIZON is the time in months chosen to analyse the stability of the label (default is 36)
```

2022-10-05 16:00 UTC, mdiazmel commented on clinicadl/tsvtools/split/split.py
> +    df_to_tsv(name, results_path, train_df, baseline=True)
```suggestion
    df_to_tsv(name, str(results_path), train_df, baseline=True)
```

2022-10-05 16:00 UTC, mdiazmel commented on clinicadl/tsvtools/split/split.py
> +    df_to_tsv(name, results_path, long_train_df)
```suggestion
    df_to_tsv(name, str(results_path), long_train_df)
```

2022-10-06 08:54 UTC, mdiazmel approved these changes
LGTM! 
I'll merge.
Note: tests for tsvtools are failing because they need the data provided by PR #350 (to be merged soon).

2022-10-06 08:55 UTC, merged