Logger updates
aramis-lab/clinicadl pull request #342
Opened 2022-09-08 15:15 UTC by ravih18

In this PR I propose a new logger for clinicadl with new handlers and new formatters.

Now the default logging mode is `INFO` and adding the `-v` verbose option sets the logger in `DEBUG`.

By default, the INFO and WARNING will be handled by stdout, by a minimal formatting (Hour:Min:Sec - Message). Then is the verbose option is passed, the logger will save the detailed logs in a `clinicadl_debug.log` file in the format `date time - name - level - message`.

I addition, as specified in Issue #295, I named the loggers of the different modules (maps_manager, task_manager...) with a specific name.

2022-09-09 15:39 UTC, camillebrianceau approved these changes

2022-09-14 15:35 UTC, mdiazmel requested changes
Hi,
A couple of comments to be discussed/fixed about the usage of loggers.

2022-09-14 15:35 UTC, mdiazmel commented on clinicadl/utils/maps_manager/__init__.py
> +from ..logwriter import LogWriter
Change to use absolute paths
```suggestion
from clinicadl.utils.logwriter import LogWriter
```

2022-09-14 15:35 UTC, mdiazmel commented on clinicadl/utils/logwriter.py
> +    ch_info = StreamHandler(stdout)
I would add this, to be have more autodocumented code:
```suggestion
    ch_info = StreamHandler(stream=sys.stdout)
```

2022-09-14 15:35 UTC, mdiazmel commented on clinicadl/utils/logwriter.py
> +def setup_logging(verbose: bool = False) -> None:
I would rather be in favor of putting this function inside `cmdline.py` and keep the class `LogWriter` and the file `logwriter.py` on the original location (this class only concerns the MAPS operations).

2022-09-14 15:35 UTC, mdiazmel commented on clinicadl/utils/logwriter.py
>      logger = getLogger("clinicadl")
Call this `clinicadl_logger` to avoid confusion with a `root` logger.

2022-09-14 15:35 UTC, mdiazmel commented on clinicadl/utils/logwriter.py
> +    fh = FileHandler("clinicadl_debug.log")
```suggestion
    file_handler = FileHandler("clinicadl_debug.log")
```

2022-09-14 15:35 UTC, mdiazmel commented on clinicadl/utils/logwriter.py
> +    ch_warning = StreamHandler(stdout)
As discussed, try to keep a single handler for the console (`console_handler`), not two (`ch_info`, `ch_warning`).

2022-09-14 15:35 UTC, mdiazmel commented on clinicadl/utils/logwriter.py
>      stderr = StreamHandler(stderr)
To verify where error messages are sent in runtime.

2022-09-16 08:57 UTC, ravih18 commented on clinicadl/utils/logwriter.py
>      logger = getLogger("clinicadl")
I am not sure if I understand how does the `root` logger work, will it be named `clinicadl` as well ?

2022-09-16 08:57 UTC, ravih18 commented on clinicadl/utils/logwriter.py
>      stderr = StreamHandler(stderr)
It seems to work.

2022-09-16 08:58 UTC, ravih18 commented
I changed the formatter as requested, I created a custom class to reduce it to a single handler.

2022-09-28 12:36 UTC, mdiazmel approved these changes
LGTM! 
Thanks @ravih18 . I'll merge it!

2022-09-28 12:42 UTC, mdiazmel commented on clinicadl/utils/logwriter.py
>      logger = getLogger("clinicadl")
> I am not sure if I understand how does the `root` logger work, will it be named `clinicadl` as well ?

Mi suggestion was to change the name of the log object (here called `logger`)  to `clinicadl_logger`, to improve readability. But it's not a big deal.

2022-09-28 12:43 UTC, merged