Cb tsvtools finish
aramis-lab/clinicadl pull request #354
Opened 2022-10-12 13:01 UTC by camillebrianceau

This PR is  the continuation of the [PR #338 ](https://github.com/aramis-lab/clinicadl/pull/338)
It aims to adapt the training part of clinicaDL to the new tsvtools.

2023-02-06 13:20 UTC, ravih18 commented on clinicadl/train/train.py
> +    maps_manager = MapsManager(maps_dir, train_dict, verbose="debug")
I don't think the default mode should be "debug"

2023-02-06 13:20 UTC, ravih18 commented on clinicadl/tsvtools/kfold/kfold.py
> +    print(list_columns)
is it necessary ?

2023-02-06 13:20 UTC, ravih18 commented on clinicadl/tsvtools/kfold/kfold.py
> +            raise ClinicaDLArgumentError(
I think this could be a TSV error more than an Argument error.

2023-02-06 13:20 UTC, ravih18 commented on clinicadl/tsvtools/kfold/kfold.py
> +    print(list_columns)
Is it necessary ?

2023-02-06 13:20 UTC, ravih18 commented on clinicadl/tsvtools/kfold/kfold_cli.py
> +@click.option(
Why do we need merge tsv for the kfold ?

2023-02-06 13:20 UTC, ravih18 commented on clinicadl/tsvtools/split/split.py
> +        if n_test > 0:
I think this can be an `elif`

2023-02-06 13:20 UTC, ravih18 commented on clinicadl/tsvtools/split/split_cli.py
> +    help="If given, use all columns to balance the split",
The help may be a little more explicit.

2023-02-06 13:20 UTC, ravih18 commented on clinicadl/utils/cli_param/argument.py
> +input_dir = click.argument("input_dir", type=click.Path(exists=True))
I think input and output are not clear enough, maybe we could find some better argument names.

2023-02-06 13:20 UTC, ravih18 commented on clinicadl/utils/split_manager/split_manager.py
> +        # for diagnosis in cohort_diagnoses:
remove the comments that are not necessary

2023-02-07 09:56 UTC, camillebrianceau commented on clinicadl/tsvtools/kfold/kfold_cli.py
> +@click.option(
With the new tsvtools, the output of all the pipelines are TSV files that just contain `["participants_tsv", "subjects_tsv"]`. Usually the pipeline tries to fetch a `labels.tsv` file but if it is not there or if it has another name, this option allows to give the path to this file. The option should however have another name because the TSV is not necessarily a `merged.tsv`.

2023-02-07 10:20 UTC, mdiazmel requested changes
Hi @camillebrianceau ,
I did a first pass, seems ok. Just a couple of comments about the docstrings and the variable names. Can merge after that.

2023-02-07 10:20 UTC, mdiazmel commented on clinicadl/tsvtools/adapt/adapt.py
> +def concat_files(file_path, df_baseline, df_all):
Add minimal docstring to explain what the function does. In new functions, try to add type hints.

2023-02-07 10:20 UTC, mdiazmel commented on clinicadl/tsvtools/adapt/adapt.py
> +def adapt(old_tsv_dir: str, new_tsv_dir: str, subset_name="labels", labels_list="AD"):
Same here, add minimal docstring.

2023-02-07 10:20 UTC, mdiazmel commented on clinicadl/tsvtools/adapt/adapt_cli.py
> +def cli(input_dir, output_dir, labels_list=None):
Here, it's important to add a clear docstring. In fact, CLI uses this docstring to show information in the command line to the user.

2023-02-07 10:20 UTC, mdiazmel commented on clinicadl/tsvtools/prepare_experiment/prepare_experiment_cli.py
> +    data_tsv2 = results_path / "train.tsv"
Use explicit variable names. For this case, it could be something like `data_tsv_train`, for example.

2023-02-08 17:12 UTC, ravih18 commented on clinicadl/tsvtools/analysis/analysis.py
> +                logger.warn(
I think it is `logger.warning` instead of `logger.warn`.

2023-02-08 17:12 UTC, ravih18 commented on clinicadl/tsvtools/kfold/kfold.py
> +            except ClinicaDLTSVError:
The error seems to be raised 3 times.

2023-02-08 17:12 UTC, ravih18 commented on clinicadl/tsvtools/prepare_experiment/prepare_experiment_cli.py
> +    data_tsv_train = results_path / "train.tsv"
I would keep `tsv`at the end of the variable name: `train_data_tsv` or `train_tsv` would be better.

2023-02-08 17:12 UTC, ravih18 commented on clinicadl/tsvtools/prepare_experiment/prepare_experiment_cli.py
> +    data_df = pd.read_csv(data_tsv_train, sep="\t")
I would use a more comprehensive variable name, `train_df` for instance.

2023-02-08 17:12 UTC, ravih18 commented on clinicadl/tsvtools/prepare_experiment/prepare_experiment_cli.py
> +        data_df2 = pd.read_csv(data_tsv, sep="\t")
Same, data_df2 is not clear enough

2023-02-08 17:12 UTC, ravih18 commented on clinicadl/tsvtools/split/split.py
> +    elif n_test > 0:
I think my previous comment was wrong, maybe you can not use elif here, to be checked.

2023-02-10 15:35 UTC, merged