Cb pet qc
aramis-lab/clinicadl pull request #361
Opened 2023-01-04 13:13 UTC by camillebrianceau

DRAFT

2023-02-03 14:29 UTC, ravih18 commented on clinicadl/quality_check/pet_linear/cli.py
> +    default=0.9,
I think it is better to put a lower threshold as safety margin.

2023-02-03 14:29 UTC, ravih18 commented on clinicadl/quality_check/pet_linear/cli.py
> +@click.argument(
It should be same as Clinica pet-linear pipeline.

2023-02-03 14:29 UTC, ravih18 commented on clinicadl/quality_check/pet_linear/cli.py
> +    "ref_region",
Same, it should have the same name and choice as clinica.

2023-02-03 14:29 UTC, ravih18 commented on clinicadl/quality_check/pet_linear/quality_check.py
> +    cache_clinicadl = path.join(home, ".cache", "clinicadl", "mask")
I think we store the ressources in the `ressources` folder, to be confirmed.

2023-02-03 14:29 UTC, ravih18 commented on clinicadl/quality_check/pet_linear/quality_check.py
> +            raise IOError("Unable to download required mni file for QC:", err)
MNI in upper case

2023-02-03 14:29 UTC, ravih18 commented on clinicadl/quality_check/pet_linear/quality_check.py
> +    def parallelize_subjects(subject, results_df):
Is it necessary to define this function inside the quality_check function ?

2023-02-03 14:29 UTC, ravih18 commented on clinicadl/quality_check/pet_linear/utils.py
> +def thresholdOtsuDisplay(image):
Use the same convention for function name -> threshold_otsu_display

2023-02-03 14:29 UTC, ravih18 commented on clinicadl/quality_check/pet_linear/utils.py
> +def normalize_homemade(image_np):
I think there should be an easier way to normalize an image.

2023-02-03 14:29 UTC, ravih18 commented on clinicadl/quality_check/pet_linear/utils.py
> +def extract_mask(img_np):
Isn't the mask already processed ?

2023-02-03 14:29 UTC, ravih18 commented on clinicadl/quality_check/pet_linear/utils.py
> +    img_seuil_35 = copy(img_np)
keep the variable name in english

2023-02-03 14:29 UTC, ravih18 commented on clinicadl/quality_check/pet_linear/utils.py
> +    xx = int(shape3D[0])
Why is there a need of int ?

2023-02-03 14:29 UTC, ravih18 commented on clinicadl/quality_check/pet_linear/utils.py
> +    for i in range(xx):
There is probably an easier method in numpy to do this.

2023-02-03 14:29 UTC, ravih18 commented on clinicadl/quality_check/pet_linear/cli.py
> +    """Performs quality check on t1-volume pipeline.
docstring to update

2023-02-03 14:29 UTC, ravih18 commented on docs/Preprocessing/QualityCheck.md
> +!!! mettre les liens des articles plus récents !!
à faire

2023-02-03 14:29 UTC, ravih18 commented on docs/Preprocessing/QualityCheck.md
> +prior to running this task.) --> not anymore
remove

2023-02-03 14:29 UTC, ravih18 commented on docs/Preprocessing/QualityCheck.md
> +- `--network` (str) is the name of the network you want to use (to choose between sq101, darq resnet18, deepQC resnet18)
it is already in the other PR

2023-02-03 14:29 UTC, ravih18 commented on docs/Preprocessing/QualityCheck.md
> +You can find [here](https://github.com/camillebrianceau/QC) all the process to create the mask and the differents experiments that have been made to chose the best metric.
"you can find in the repository", and maybe put a link to and Aramis lab repo.

2023-02-03 14:29 UTC, ravih18 commented on docs/Preprocessing/QualityCheck.md
> +TO CHANGE !!!
to do

2023-02-03 14:48 UTC, ravih18 reviewed
It would be great to generally use the numpy existing function to manipulate array and also add docstrings to function so it is easier to understand what they can be used for.

2023-02-03 16:02 UTC, camillebrianceau commented on clinicadl/quality_check/pet_linear/quality_check.py
> +    cache_clinicadl = path.join(home, ".cache", "clinicadl", "mask")
I don't know about that, I was thinking that now we have to store everything on the web server (and on AWS after)

2023-02-03 16:37 UTC, camillebrianceau commented on clinicadl/quality_check/pet_linear/utils.py
> +    xx = int(shape3D[0])
no need lol

2023-02-03 17:20 UTC, ravih18 commented on clinicadl/quality_check/pet_linear/quality_check.py
> +    cache_clinicadl = path.join(home, ".cache", "clinicadl", "mask")
yes, I was more thinking about when it is downloaded, I don't know if it is better to put it in a cache (which might be the best solution) or put it is the ressources of the repo (which is, I believe, what we do for the other downloaded files).

2023-03-24 13:10 UTC, ravih18 commented on clinicadl/quality_check/pet_linear/utils.py
> +def normalize_homemade(image_np):
Use what exists.

2023-03-29 16:58 UTC, ravih18 requested changes

2023-03-29 16:58 UTC, ravih18 commented on clinicadl/quality_check/pet_linear/cli.py
> +    default=0.5,
Didn't we decide to put the threshold at 0.8 or 0.9 ?

2023-03-29 16:58 UTC, ravih18 commented on clinicadl/quality_check/pet_linear/utils.py
> +    img_norm_thresh = norm(img_copy)
This can directly be writen as follow: img_norm_thresh = MinMaxNormalization()(img_copy)

2023-03-29 16:58 UTC, ravih18 commented on clinicadl/quality_check/pet_linear/utils.py
> +def distance(contour_np, image_np):
The name of the function is not very appropriate and we do not really compute a distance.

2023-03-29 16:58 UTC, ravih18 commented on clinicadl/quality_check/pet_linear/quality_check.py
> +    )
This needs to be done only if the file is not already in the cache, no ?

2023-03-29 16:58 UTC, ravih18 commented on clinicadl/quality_check/pet_linear/quality_check.py
> +    inside = 0  # 1605780
what does this part do ? If i understand well it counts the one in the mask_contour, then they should be a function directly returning this value in numpy.

2023-03-29 16:58 UTC, ravih18 commented on clinicadl/quality_check/pet_linear/quality_check.py
> +    def parallelize_subjects(subject, results_df):
The name of the function is not very clear.

2023-03-29 16:58 UTC, ravih18 commented on clinicadl/quality_check/pet_linear/quality_check.py
> +                / (
Use f strings

2023-03-29 16:58 UTC, ravih18 commented on clinicadl/quality_check/pet_linear/quality_check.py
> +        if not participants_tsv is None:
i don't understand this in python, how can `not x` be None ? maybe you mean `if participants_tsv is not None` ?

2023-03-29 16:58 UTC, ravih18 commented on clinicadl/quality_check/pet_linear/quality_check.py
I think this should be rewritten using Clinica methods to read files in the CAPS: clinica_file_reader. This would be more consistant with other ClinicaDL functions.
Moreover if Clinica changes something is the CAPS, then clinica_file_reader will be adapted, so the pipeline won't be broken.
And finally it might be much more easier to parallelize the pipeline over the file list returned by Clinica as it is a list.

2023-03-29 16:58 UTC, ravih18 commented on docs/Preprocessing/QualityCheck.md
> +We manually checked a few image sets, among which 69 images were misregistered. For these images, the sum of pixels within the contour mask was high, and using this metric, the pipeline detected 80%
69 over how many ? Not sure if this figure is relevant.

2023-03-31 12:41 UTC, camillebrianceau commented on clinicadl/quality_check/pet_linear/quality_check.py
done in [d6c8e5c](https://github.com/aramis-lab/clinicadl/pull/361/commits/d6c8e5cc9f3d48e1fe0b9a9fc32fca554cb9af65)

2023-04-03 12:09 UTC, ravih18 approved these changes
Can be merged

2023-04-03 12:23 UTC, merged