Transition from os to patelin
aramis-lab/clinicadl pull request #395
Opened 2023-03-08 16:18 UTC by camillebrianceau

2023-03-16 14:20 UTC, ravih18 approved these changes
I am not super familiar with pathlib but LGTM.

2023-03-16 14:20 UTC, ravih18 commented on clinicadl/utils/maps_manager/iotools.py
> +    process = multiprocessing.current_process()
Does this do that same ? If we are not sure we can still keep os sometimes for this kind of function.

2023-03-16 14:36 UTC, camillebrianceau commented on clinicadl/utils/maps_manager/iotools.py
> +    process = multiprocessing.current_process()
Yes it does, but it imports `multiprocessing` instead of `os` so I don't know if it is really relevant ...

2023-03-22 09:33 UTC, mdiazmel requested changes
Hi @camillebrianceau,

Thanks for taking in charge this task, that is not trivial.

It's a good starting point. In a next iteration, I will propose to review the arguments for the functions that do I/O operations, in order to change the type. For example, variables as `output_dir`, `img_path`, `tsv_dir`, etc. should be declared in the function definition as of type `Path`  and not `str`. It's a lot of work, and as I said before, it can be done in a next PR.

Concerning this PR, globally, I think that you have to review where the cast to the `Path` object is really necessary and where isn't (I pointed our some examples in the comments of the review).

2023-03-22 09:33 UTC, mdiazmel commented on clinicadl/generate/generate.py
> +    cache_clinicadl = Path(home) / ".cache" / "clinicadl" / "ressources" / "masks"
Here, It seems redundant with the code in the above line. I would remove the precedent line and add"
```suggestion
    home = Path.home()
    cache_clinicadl = home / ".cache" / "clinicadl" / "ressources" / "masks"
```

2023-03-22 09:33 UTC, mdiazmel commented on clinicadl/generate/generate.py
> +    Path(cache_clinicadl).mkdir(parents=True, exist_ok=True)
It's necessary to cast with `Path(...)`? It seems that `cache_clinicadl` is already a `Path` object.

2023-03-22 09:33 UTC, mdiazmel commented on clinicadl/generate/generate.py
> +        if not (Path(cache_clinicadl) / "AAL2").is_dir():
Same than above

2023-03-22 09:33 UTC, mdiazmel commented on clinicadl/generate/generate.py
> +                    mask_path = Path(cache_clinicadl) / "AAL2"
Same

2023-03-22 09:33 UTC, mdiazmel commented on clinicadl/generate/generate.py
> +            mask_path = Path(cache_clinicadl) / "AAL2"
Same

2023-03-22 09:33 UTC, mdiazmel commented on clinicadl/prepare_data/prepare_data.py
> +            if not Path(output_file_dir).is_dir():
Not necessary to cast to Path
```suggestion
            if not output_file_dir.is_dir():
```

2023-03-22 09:33 UTC, mdiazmel commented on clinicadl/quality_check/t1_linear/quality_check.py
> +    cache_clinicadl = Path(home) / ".cache" / "clinicadl" / "models"
Same comment than before, not necessary to cast `Path(home)` if the precedent line is edited.

2023-03-22 09:33 UTC, mdiazmel commented on clinicadl/quality_check/t1_linear/quality_check.py
Globally, the comment is the same. You should review where the cast to a `Path` object is pertinent or not. For example, for the variable  `cache_clinicadl` isn't necessary because it's already a `Path` object.

2023-03-22 09:33 UTC, mdiazmel commented on tests/test_train_ae.py
> +    # with open(tmp_out_dir / "maps.json", "r") as out:
Why theses assertions are commented?

2023-03-22 12:01 UTC, camillebrianceau commented
Hi @mdiazmel,

Thank you for your review.

I agree that we need another PR to change the type of variables declared as `str` for `Path`. We also need to change the `click.option` type in some cases.

I've done a preliminary review to identify where the cast to the Path object is really necessary. If it's okay, I'd like to merge this PR and address any remaining changes in the next PR.

2023-03-22 13:46 UTC, merged