Cb generate hypometabolic
aramis-lab/clinicadl pull request #397
Opened 2023-03-13 15:14 UTC by camillebrianceau

- This PR aims to add a pipeline that generates hypometabolic data. (for more information, see https://hal.science/hal-03835015)
- For the output filename, we will add a flag `desc-hypo-pathology-degree`. For example, the filename:
`sub-ADNI098S6658_ses-M00_trc-18FFDG_rec-uniform_pet_space-MNI152NLin2009cSym_desc-Crop_res-1x1x1_suvr-cerebellumPons2_pet.nii` would become:
`sub-ADNI098S6658_ses-M00_trc-18FFDG_rec-uniform_pet_space-MNI152NLin2009cSym_desc-Crop_res-1x1x1_suvr-cerebellumPons2_pat-ad_deg-30_pet.nii`.
- The TSV files produced are `subject_session_list.tsv`, which is the same as in the CAPS, and `data.tsv`, which contains information on the pathology and the degree of the pathology applied.

2023-03-17 11:27 UTC, ravih18 requested changes
Several changes are required:
* Some steps should be done at initialisation and not in the loop (mask generation)
* We should think about the tsv produced, the one used in other generate pipeline would not work in this case.
* The name of the output file should be debated.

2023-03-17 11:27 UTC, ravih18 commented on clinicadl/generate/generate.py
> +    Generates a dataset, based on the images of the CAPS directory, where a
Description to change

2023-03-17 11:27 UTC, ravih18 commented on clinicadl/generate/generate.py
> +        atrophy_percent: percentage of atrophy applied.
It is not an atrophy, it is an hypometabolism

2023-03-17 11:27 UTC, ravih18 commented on clinicadl/generate/generate.py
> +    pathology_percent: float = 60,
I think default should be 30

2023-03-17 11:27 UTC, ravih18 commented on clinicadl/generate/generate.py
> +        atrophy_percent: percentage of atrophy applied.
I think more globally that the args list have not been updated

2023-03-17 11:27 UTC, ravih18 commented on clinicadl/generate/generate.py
> +    dementias = ["ad", "bvftd", "lvppa", "nfvppa", "pca", "svppa"]
It looks like this is not coherent with the default argument of the function

2023-03-17 11:27 UTC, ravih18 commented on clinicadl/generate/generate.py
> +    pathology: str = "alzheimer",
"alzheimer" or "ad" ?

2023-03-17 11:27 UTC, ravih18 commented on clinicadl/generate/generate.py
> +    dementias = ["ad", "bvftd", "lvppa", "nfvppa", "pca", "svppa"]
I think this should not be hard coded here, maybe more in the choice available in the command line.

2023-03-17 11:27 UTC, ravih18 commented on clinicadl/generate/generate.py
> +    if pathology_percent >= 70:
Maybe sigma should be an argument of the command line ? Default would be 5 then

2023-03-17 11:27 UTC, ravih18 commented on clinicadl/generate/generate.py
> +    diagnosis_list = ["AD", "CN"]
Is this relevant ? First all the simulated images are diseased, and then they are more demantias than just AD

2023-03-17 11:27 UTC, ravih18 commented on clinicadl/generate/generate.py
> +        image_paths = clinica_file_reader(
Can this be called only once instead of at each iteration ?

2023-03-17 11:27 UTC, ravih18 commented on clinicadl/generate/generate.py
> +        mask_nii = resample_to_img(mask_nii, image_nii, interpolation="nearest")
This can be done only once

2023-03-17 11:27 UTC, ravih18 commented on clinicadl/generate/generate.py
> +            60,
What is 60 ?

2023-03-17 11:27 UTC, ravih18 commented on clinicadl/generate/generate.py
> +            "F",
What is F ?

2023-03-17 11:27 UTC, ravih18 commented on clinicadl/generate/generate.py
> +            diagnosis_list[label],
Do we need diagnosis in simulated dementia ? This might not be relevant

2023-03-17 11:27 UTC, ravih18 commented on clinicadl/generate/generate.py
> +        row = [
A column with pathology and percentage could be better

2023-03-17 11:27 UTC, ravih18 commented on clinicadl/generate/generate.py
> +    logger.info(f"hypometabolic dataset was generated at {output_dir}")
Make a sentence, h->H and add a dot.

2023-03-17 11:27 UTC, ravih18 commented on clinicadl/generate/generate.py
> +    logger.info(f"hypometabolic dataset was generated at {output_dir}")
Maybe also add the parameters (pathology and percentage in this log).

2023-03-17 11:27 UTC, ravih18 commented on clinicadl/generate/generate_hypometabolic_cli.py
> +    default=60.0,
default should be 30

2023-03-17 11:27 UTC, ravih18 commented on clinicadl/generate/generate_hypometabolic_cli.py
> +    help="Percentage of pathology applied.",
"Percentage of hypometabolism simulated."

2023-03-17 11:27 UTC, ravih18 commented on clinicadl/generate/generate_hypometabolic_cli.py
> +    "--pathology",
maybe dementia would be more accurate.

2023-03-17 11:27 UTC, ravih18 commented on clinicadl/generate/generate_hypometabolic_cli.py
> +@cli_param.option.n_subjects
I think this information is in participant list no ?

2023-03-17 11:27 UTC, ravih18 commented on clinicadl/generate/generate_hypometabolic_cli.py
> +        acq_label="18FFDG",
These argument should be the one passed in the command line ? Otherwise we can just remove them from the CLI

2023-03-17 11:27 UTC, ravih18 commented on clinicadl/generate/generate_utils.py
> +def hypo_synthesis(image, mask, percentage, sigma):
The mask processing should be done only once when the mask is loaded, not everytime we compute a subject.

2023-03-17 11:27 UTC, ravih18 commented on clinicadl/generate/hypometabolic.py
This file should be removed from the repo.

2023-03-17 11:27 UTC, ravih18 commented on docs/Preprocessing/Generate.md
To complete.

2023-03-29 14:47 UTC, camillebrianceau commented on clinicadl/generate/generate_hypometabolic_cli.py
> +@cli_param.option.n_subjects
Yes but `participant_list` is an option so you can chose which one you want to add (or don't add any)

2023-03-29 17:15 UTC, ravih18 requested changes
We still need to agree on the output file name. In my opinion it should follow the original dataset name, with a flag `desc-hypo_ad_30` for instance for 30% of AD.
Indeed the goal is to be able to find to which subject does the abnormal image belongs.

2023-03-29 17:15 UTC, ravih18 commented on clinicadl/generate/generate_hypometabolic_cli.py
> +    help="Path to the extracted masks to generate the two labels. "
The help string should be updated.

2023-03-29 17:15 UTC, ravih18 commented on clinicadl/generate/generate_hypometabolic_cli.py
> +    "-ad",
I think this might be confusing with the name of the pathology, maybe -anod ?

2023-03-29 17:15 UTC, ravih18 commented on clinicadl/generate/generate_hypometabolic_cli.py
> +    help="sigma ?",
it is the parameter of the gaussian filter used for smoothing.

2023-03-29 17:15 UTC, ravih18 commented on clinicadl/generate/generate.py
> +    from pathlib import Path
already imported

2023-03-29 17:15 UTC, ravih18 commented on clinicadl/generate/generate.py
> +    from clinicadl.utils.exceptions import DownloadError
should be imported l22 ?

2023-03-29 17:15 UTC, ravih18 commented on clinicadl/generate/generate.py
> +    if mask_path is None:
mask_path will always be None, does it needs to be tested ?

2023-03-29 17:15 UTC, ravih18 commented on clinicadl/generate/generate.py
> +                mask_nii = nib.load(mask_path)
this can be outside of the if..else

2023-03-29 17:15 UTC, ravih18 commented on clinicadl/generate/generate.py
> +            mask_nii = nib.load(mask_path)
this can be outside of the if..else

2023-03-29 17:15 UTC, ravih18 commented on clinicadl/generate/generate.py
> +    mask_resample_nii = resample_to_img(mask_nii, image_nii, interpolation="nearest")
maybe these two steps can also be in the mask_processing function

2023-03-29 17:15 UTC, ravih18 commented on clinicadl/generate/generate.py
> +        # for i in range(n_subjects):
remove this comment

2023-03-29 17:15 UTC, ravih18 commented on clinicadl/generate/generate.py
> +            f"sub-HYPO{i}_{pathology}-{anomaly_degree}_{sessions[i]}_{filename_pattern}"
I think we should still have the original dataset ID since the goal is to have a patient specific abnormal image.

2023-03-30 12:47 UTC, camillebrianceau commented on clinicadl/generate/generate.py
> +    mask_resample_nii = resample_to_img(mask_nii, image_nii, interpolation="nearest")
It would require to add the `image_nii` as a parameters of the function ..

2023-03-30 15:46 UTC, merged