Add `--save_nifti` option for ìnterpret`
aramis-lab/clinicadl pull request #398
Opened 2023-03-16 09:50 UTC by camillebrianceau

I added an option (--save_nifti) to save the interpretation map (individual or groups) in nifty format because it was only saved in PyTorch tensors format.

2023-03-16 20:33 UTC, ravih18 requested changes
Lokks good, just a few comment to address.

2023-03-16 20:33 UTC, ravih18 commented on clinicadl/utils/maps_manager/maps_manager.py
> +            print(data_test)
print should be removed

2023-03-16 20:33 UTC, ravih18 commented on clinicadl/utils/maps_manager/maps_manager.py
> +            print(test_loader)
print should be removed

2023-03-16 20:33 UTC, ravih18 commented on clinicadl/utils/maps_manager/maps_manager.py
> +                    # map_pt: np.array
should be removed

2023-03-16 20:33 UTC, ravih18 commented on clinicadl/utils/maps_manager/maps_manager.py
> +                                single_nifti_path = path.join(
to change with pathlib

2023-03-16 20:33 UTC, ravih18 commented on clinicadl/utils/maps_manager/maps_manager.py
> +                            path.join(results_path, f"mean_{self.mode}-{i}_map.nii.gz"),
to change with pathlib

2023-03-16 20:33 UTC, ravih18 commented on clinicadl/interpret/interpret_cli.py
> +@click.option(
Check if the option cannot be gathered with the one of predict

2023-03-22 09:39 UTC, mdiazmel approved these changes
Looks Ok!

2023-03-23 09:15 UTC, ravih18 approved these changes
Can be merged !

2023-03-23 09:17 UTC, merged