Cb wandb
aramis-lab/clinicadl pull request #453
Opened 2023-06-27 13:01 UTC by camillebrianceau

test

2023-06-28 11:36 UTC, mdiazmel requested changes
Hi @camillebrianceau ,

I'm definitely against adding experiment trackers to the code base of ClinicaDL. They will be added as optional dependencies (as the docs dependencies in the pyproject file) and you should find a way to import the modules not directly in the `maps manager` but in the specific functions/classes where they are really used. If we decide to integrated, W&B and MLFlow should be optional packages not necessary to the *standard* way  of using ClinicaDL.

2023-08-22 14:16 UTC, mdiazmel requested changes
Seems ok. I think that it's important to freeze the mlflow version in order to guarantee compatibility with the autolog function (which depends also the the Pytorch version). 
Let me know when the suggested changes will be implemented, I will launch a new mlflow server to test if the feature works as planned.

2023-08-22 14:16 UTC, mdiazmel commented on clinicadl/utils/tracking_exp.py
> +        self._mlflow.autolog()
Have you tested if the autolog functionality of _mlflow_ works well with Pytorch? [According to the documentation](https://mlflow.org/docs/latest/python_api/mlflow.pytorch.html), it's only available for a range of versions. We should probably reflects this in our dependency file.

2023-08-22 14:16 UTC, mdiazmel commented on pyproject.toml
> +mlflow = "*"
Use `mlflow = ^2.6.0` which currently support autologin for `1.6.0 <= torch <= 2.0.1` . Other mlflow versions support different Pytorch versions.

2023-08-22 14:21 UTC, mdiazmel commented
We still need to verify why the GPU tests fail for this PR.

2023-09-07 13:09 UTC, ravih18 commented on clinicadl/utils/cli_param/train_option.py
> +    help="Use `--track_exp` to enable wandb to track your experience.",
The help string can be improved (wand and mlflow). Maybe explain a bit what do you mean by tracking, is experience a training job ? etc

2023-09-07 13:09 UTC, ravih18 commented on clinicadl/utils/tracking_exp.py
> +class Tracker:
add doc strings if possible.

2023-09-07 13:09 UTC, ravih18 commented on clinicadl/utils/tracking_exp.py
> +class WandB_class(Tracker):
i am not sure it is necessary to have `class` in the class name, maybe `MLflow_handler` or something like that would sound better.

2023-09-07 13:09 UTC, ravih18 commented on clinicadl/utils/tracking_exp.py
> +class Mlflow_class(Tracker):
same comment

2023-09-07 14:34 UTC, ravih18 approved these changes

2023-09-12 08:50 UTC, merged